name: Build & Publish IGV Webapp

on:
  push:
    branches:    
      - dev
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Publish Docker Image
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Configure environment
      id: config
      run: |
        DOCKER_TAG=$(echo ${GITHUB_REF} | grep 'tags' | sed -e 's/refs\/tags\///')
        echo ::set-output name=version::$DOCKER_TAG

    - name: Publish docker
      id: docker-dev
      uses: yjcyxky/docker-action@master
      if: github.ref == 'refs/heads/dev'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.cn-shanghai.aliyuncs.com/pgx-docker-registry
        repository: igv-webapp
        tag: ${{ steps.config.outputs.version }}
        flag: test

    - name: Publish docker
      id: docker-master
      uses: yjcyxky/docker-action@master
      if: github.ref == 'refs/heads/tgmc-master'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.cn-shanghai.aliyuncs.com/pgx-docker-registry
        repository: igv-webapp
        tag: ${{ steps.config.outputs.version }}

    - name: Dingtalk Robot Message
      uses: fifsky/dingtalk-action@master
      if: success()
      with:
        url: ${{ secrets.DINGTALK_WEBHOOK }}
        type: markdown
        content: |
          #### [SUCCESS] IGV Webapp 镜像自动构建
          点击 [igv-webapp](https://github.com/clinico-omics/igv-webapp) 查看详情
        at: Choppy Team

    - name: Dingtalk Robot Message
      uses: fifsky/dingtalk-action@master
      if: failure()
      with:
        url: ${{ secrets.DINGTALK_WEBHOOK }}
        type: markdown
        content: |
          #### [FAILED] IGV Webapp 镜像自动构建
          点击 [igv-webapp](https://github.com/clinico-omics/igv-webapp) 查看详情
        at: Choppy Team